// <auto-generated />
using System;
using ApiProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProject.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005102243_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiProject.Api.Entities.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirmaKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirmaKodu")
                        .IsUnique();

                    b.ToTable("Firma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            FirmaAdi = "ABC Teknoloji",
                            FirmaKodu = "ABC",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            FirmaAdi = "XYZ Lojistik",
                            FirmaKodu = "XYZ",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaAyar", b =>
                {
                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<string>("Dil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("tr-TR");

                    b.Property<string>("EkAyarlarJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TemaRengi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZamanDilimi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Europe/Istanbul");

                    b.HasKey("FirmaId");

                    b.ToTable("FirmaAyar", null, t =>
                        {
                            t.HasCheckConstraint("CK_FirmaAyar_EkAyarlarJson", "[EkAyarlarJson] IS NULL OR ISJSON([EkAyarlarJson]) = 1");
                        });

                    b.HasData(
                        new
                        {
                            FirmaId = 1,
                            Dil = "tr-TR",
                            EkAyarlarJson = "{\"destekTelefonu\":\"0212 000 00 00\",\"modulStok\":true}",
                            GuncellemeTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "https://abc.ornek.com/logo.png",
                            TemaRengi = "#1E88E5",
                            ZamanDilimi = "Europe/Istanbul"
                        },
                        new
                        {
                            FirmaId = 2,
                            Dil = "en-US",
                            EkAyarlarJson = "{\"destekTelefonu\":\"+44 20 0000 0000\",\"modulStok\":false}",
                            GuncellemeTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "https://xyz.ornek.com/logo.png",
                            TemaRengi = "#43A047",
                            ZamanDilimi = "Europe/London"
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .IsUnicode(false)
                        .HasColumnType("varchar(253)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("FirmaId");

                    b.ToTable("FirmaDomain", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Domain = "abc.localhost",
                            FirmaId = 1,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 2,
                            Domain = "abc.ornek.com",
                            FirmaId = 1,
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = 3,
                            Domain = "xyz.localhost",
                            FirmaId = 2,
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = 4,
                            Domain = "xyz.ornek.com",
                            FirmaId = 2,
                            VarsayilanMi = false
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<int>("HataliGirisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KilitBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizeKullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "NormalizeKullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "ABC Yönetici",
                            AktifMi = true,
                            Email = "admin@abc.ornek.com",
                            FirmaId = 1,
                            HataliGirisSayisi = 0,
                            KullaniciAdi = "admin",
                            NormalizeKullaniciAdi = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "AQAAAAIAAYagAAAAEK7v3g7bOp36PP3Pt7XkS2ojtYQEV+xmJhHfv4IlNTvFfB/NvtBp/7YvrsT7oR7ZmA=="
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "XYZ Yönetici",
                            AktifMi = true,
                            Email = "admin@xyz.ornek.com",
                            FirmaId = 2,
                            HataliGirisSayisi = 0,
                            KullaniciAdi = "admin",
                            NormalizeKullaniciAdi = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "AQAAAAIAAYagAAAAEHmK/9vv7Kzqx3rpwssF1OXu0reqQ5Q7zWSuv1u86VH45HQ5xgEQh6RrkJKJ9gjVzg=="
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaAyar", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithOne("Ayar")
                        .HasForeignKey("ApiProject.Api.Entities.FirmaAyar", "FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaDomain", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithMany("Domainler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Kullanici", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Firma", b =>
                {
                    b.Navigation("Ayar");

                    b.Navigation("Domainler");
                });
#pragma warning restore 612, 618
        }
    }
}
