// <auto-generated />
using System;
using ApiProject.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProject.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006115947_SepetEklendi")]
    partial class SepetEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiProject.Api.Entities.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirmaKodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FirmaKodu")
                        .IsUnique();

                    b.ToTable("Firma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AktifMi = true,
                            FirmaAdi = "ABC Teknoloji",
                            FirmaKodu = "ABC",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AktifMi = true,
                            FirmaAdi = "XYZ Lojistik",
                            FirmaKodu = "XYZ",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaAyar", b =>
                {
                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("tr-TR");

                    b.Property<string>("EkAyarlarJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TemaRengi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ZamanDilimi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Europe/Istanbul");

                    b.HasKey("FirmaId");

                    b.ToTable("FirmaAyar", null, t =>
                        {
                            t.HasCheckConstraint("CK_FirmaAyar_EkAyarlarJson", "[EkAyarlarJson] IS NULL OR ISJSON([EkAyarlarJson]) = 1");
                        });

                    b.HasData(
                        new
                        {
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Dil = "tr-TR",
                            EkAyarlarJson = "{\"destekTelefonu\":\"0212 000 00 00\",\"modulStok\":true}",
                            GuncellemeTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "https://abc.ornek.com/logo.png",
                            TemaRengi = "#1E88E5",
                            ZamanDilimi = "Europe/Istanbul"
                        },
                        new
                        {
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Dil = "en-US",
                            EkAyarlarJson = "{\"destekTelefonu\":\"+44 20 0000 0000\",\"modulStok\":false}",
                            GuncellemeTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogoUrl = "https://xyz.ornek.com/logo.png",
                            TemaRengi = "#43A047",
                            ZamanDilimi = "Europe/London"
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .IsUnicode(false)
                        .HasColumnType("varchar(253)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VarsayilanMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("FirmaId");

                    b.ToTable("FirmaDomain", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Domain = "abc.localhost",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Domain = "abc.ornek.com",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            VarsayilanMi = false
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Domain = "xyz.localhost",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VarsayilanMi = true
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Domain = "xyz.ornek.com",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            VarsayilanMi = false
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HataliGirisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KilitBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizeKullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YoneticiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "NormalizeKullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AdSoyad = "ABC Yönetici",
                            AktifMi = true,
                            Email = "admin@abc.ornek.com",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            HataliGirisSayisi = 0,
                            KullaniciAdi = "admin",
                            NormalizeKullaniciAdi = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "AQAAAAIAAYagAAAAEK7v3g7bOp36PP3Pt7XkS2ojtYQEV+xmJhHfv4IlNTvFfB/NvtBp/7YvrsT7oR7ZmA==",
                            YoneticiMi = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AdSoyad = "XYZ Yönetici",
                            AktifMi = true,
                            Email = "admin@xyz.ornek.com",
                            FirmaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            HataliGirisSayisi = 0,
                            KullaniciAdi = "admin",
                            NormalizeKullaniciAdi = "ADMIN",
                            OlusturmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SifreHash = "AQAAAAIAAYagAAAAEHmK/9vv7Kzqx3rpwssF1OXu0reqQ5Q7zWSuv1u86VH45HQ5xgEQh6RrkJKJ9gjVzg==",
                            YoneticiMi = true
                        });
                });

            modelBuilder.Entity("ApiProject.Api.Entities.SepetKalemi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.HasIndex("FirmaId", "KullaniciId", "UrunId")
                        .IsUnique();

                    b.ToTable("SepetKalemi", (string)null);
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Urun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Ad");

                    b.HasIndex("FirmaId", "Kod")
                        .IsUnique();

                    b.ToTable("Urun", (string)null);
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaAyar", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithOne("Ayar")
                        .HasForeignKey("ApiProject.Api.Entities.FirmaAyar", "FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.FirmaDomain", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithMany("Domainler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Kullanici", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.SepetKalemi", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", null)
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiProject.Api.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiProject.Api.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Urun", b =>
                {
                    b.HasOne("ApiProject.Api.Entities.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("ApiProject.Api.Entities.Firma", b =>
                {
                    b.Navigation("Ayar");

                    b.Navigation("Domainler");
                });
#pragma warning restore 612, 618
        }
    }
}
