@base = http://localhost:5000

### Config: ABC (Host)
GET {{base}}/api/firma/config
Host: abc.localhost

### Config: XYZ (X-Client)
GET {{base}}/api/firma/config
X-Client: XYZ

### Login: ABC (X-Client)
# @name loginAbc
POST {{base}}/api/auth/login
X-Client: ABC
Content-Type: application/json

{ "kullaniciAdi": "admin", "sifre": "Abc123!" }

### Login: XYZ (Host)
POST {{base}}/api/auth/login
Host: xyz.localhost
Content-Type: application/json

{ "kullaniciAdi": "admin", "sifre": "Xyz123!" }

### Ben
GET {{base}}/api/auth/ben
Authorization: Bearer {{loginAbc.response.body.$.token}}

### ABC token, XYZ domaini: 403
GET {{base}}/api/auth/ben
Host: xyz.localhost
Authorization: Bearer {{loginAbc.response.body.$.token}}
